yarnPath: ".yarn/releases/yarn-berry.js"

pnpMode: loose

enableTransparentWorkspaces: true

packageExtensions:
  "asn1.js@*":
    dependencies:
      vm: "*"
  cipher-base@*:
    dependencies:
      stream: "*"
  safe-buffer@*:
    dependencies:
      buffer: "*"
  "@webpack-blocks/webpack@*":
    dependencies:
      webpack: "*"
  uglifyjs-webpack-plugin@*:
    dependencies:
      webpack: "*"
  extract-text-webpack-plugin@*:
    dependencies:
      webpack: "*"
  findhelp@*:
    dependencies:
      minimist: "*"
  babel-plugin-transform-import-css@*:
    dependencies:
      "@babel/types": "*"
      "@babel/template": "*"
      generic-names: "*"
      postcss: "*"
  react-in-viewport@*:
    dependencies:
      react-dom: "*"
  "@loadable/babel-plugin@*":
    dependencies:
      "@babel/core": "^7.0.0"
  eslint-module-utils@*:
    dependencies:
      "@typescript-eslint/parser": "*"
  "@formatjs/intl-utils@*":
    dependencies:
      crypto: "*"
      path: "*"

