packageExtensions: 
  "@webpack-blocks/webpack@*":
    dependencies:
      webpack: "^4.0.0"

  uglifyjs-webpack-plugin@*:
    dependencies:
      webpack: "^4.0.0"

  extract-text-webpack-plugin@*:
    dependencies:
      webpack: "^4.0.0"

  findhelp@*:
    dependencies:
      minimist: "*"

  babel-plugin-transform-import-css@*:
    dependencies:
      "@babel/types": "*"
      "@babel/template": "*"
      generic-names: "*"
      postcss: "*"

  react-in-viewport@*:
    dependencies:
      react-dom: "*"

enableTransparentWorkspaces: true

nodeLinker: "node-modules"

# pnpEnableInlining: false
