yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
  "@webpack-blocks/webpack@*":
    peerDependencies:
      webpack: "*"

  uglifyjs-webpack-plugin@*:
    peerDependencies:
      webpack: "*"

  extract-text-webpack-plugin@*:
    peerDependencies:
      webpack: "*"

  findhelp@*:
    dependencies:
      minimist: "*"

  babel-plugin-transform-import-css@*:
    dependencies:
      "@babel/types": "*"
      "@babel/template": "*"
      generic-names: "*"
      postcss: "*"

  react-in-viewport@*:
    dependencies:
      react-dom: "*"

enableTransparentWorkspaces: true

nodeLinker: "node-modules"

# pnpEnableInlining: false
