enableTransparentWorkspaces: true

packageExtensions:
  "@formatjs/intl-utils@*":
    dependencies:
      crypto: "*"
      path: "*"
  "@loadable/babel-plugin@*":
    dependencies:
      "@babel/core": ^7.0.0
  "@webpack-blocks/webpack@*":
    dependencies:
      webpack: "*"
  asn1.js@*:
    dependencies:
      vm: "*"
  babel-plugin-transform-import-css@*:
    dependencies:
      "@babel/template": "*"
      "@babel/types": "*"
      generic-names: "*"
      postcss: "*"
  cipher-base@*:
    dependencies:
      stream: "*"
  eslint-module-utils@*:
    dependencies:
      "@typescript-eslint/parser": "*"
  extract-text-webpack-plugin@*:
    dependencies:
      webpack: "*"
  findhelp@*:
    dependencies:
      minimist: "*"
  react-in-viewport@*:
    dependencies:
      react-dom: "*"
  safe-buffer@*:
    dependencies:
      buffer: "*"
  uglifyjs-webpack-plugin@*:
    dependencies:
      webpack: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.0.0-rc.33.js
